version: '3'
services: 
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker_dog
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin4:
    image: dpage/pgadmin4:latest
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    restart: always