version: '3'
services: 
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - 5433:5432

  web: &app_base
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker_dog
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin4:
    image: dpage/pgadmin4:latest
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    restart: always

  webpack:
    <<: *app_base
    command: bash -c "rm -rf /app/public/packs; /app/bin/webpack-dev-server"
    ports:
      - "8080:8080"
    depends_on:
      - web

volumes:
  db:
  pgadmin4:
