version: '3'
services: 
  db:
    image: postgres
    volumes:
      - ./tmp/postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

  web: &app_base
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - .:/docker_dog
      - /docker_dog/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin4:
    image: dpage/pgadmin4:latest
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    restart: always

  webpack:
    <<: *app_base
    command: bash -c "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - web
    
volumes:
  pgadmin4:

